export type Persona = {
  id: string;
  name: string;
  age?: string | null;
  gender?: string | null;
  family?: string | null;
  location?: string | null;
  incomeLevel?: string | null;
  education?: string | null;
  traits?: string[] | null;
  hobbies?: string[] | null;
  jobTitle?: string | null;
  sector?: string | null;
  companySize?: string | null;
  experienceYears?: string | null;
  responsibilities?: string[] | null;
  teamStructure?: string | null;
  goals?: string[] | null;
  successDefinition?: string | null;
  ambitions?: string[] | null;
  topGoal?: string | null;
  challenges?: string[] | null;
  frustrations?: string[] | null;
  fears?: string[] | null;
  topFrustration?: string | null;
  decisionRole?: string | null;
  buyingProcess?: string[] | null;
  decisionCriteria?: string[] | null;
  alternatives?: string[] | null;
  objections?: string[] | null;
  refusalReasons?: string[] | null;
  socialNetworks?: string[] | null;
  infoSources?: string[] | null;
  contentTypes?: string[] | null;
  preferredChannels?: string[] | null;
  heardAboutUs?: string[] | null;
  reasonsToChooseUs?: string[] | null;
  differentiatorsAppreciated?: string[] | null;
  prePurchaseConcerns?: string[] | null;
  memorableExperience?: string | null;
  referralPitch?: string | null;
  shortBio?: string | null;
  quote?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type PersonaRow = {
  id: string;
  user_id: string;
  name: string;
  age: string | null;
  gender: string | null;
  family: string | null;
  location: string | null;
  income_level: string | null;
  education: string | null;
  traits: string[] | null;
  hobbies: string[] | null;
  job_title: string | null;
  sector: string | null;
  company_size: string | null;
  experience_years: string | null;
  responsibilities: string[] | null;
  team_structure: string | null;
  goals: string[] | null;
  success_definition: string | null;
  ambitions: string[] | null;
  top_goal: string | null;
  challenges: string[] | null;
  frustrations: string[] | null;
  fears: string[] | null;
  top_frustration: string | null;
  decision_role: string | null;
  buying_process: string[] | null;
  decision_criteria: string[] | null;
  alternatives: string[] | null;
  objections: string[] | null;
  refusal_reasons: string[] | null;
  social_networks: string[] | null;
  info_sources: string[] | null;
  content_types: string[] | null;
  preferred_channels: string[] | null;
  heard_about_us: string[] | null;
  reasons_to_choose_us: string[] | null;
  differentiators_appreciated: string[] | null;
  pre_purchase_concerns: string[] | null;
  memorable_experience: string | null;
  referral_pitch: string | null;
  short_bio: string | null;
  quote: string | null;
  created_at: string;
  updated_at: string;
};
